### ISSUE TITLE
Sparse solves for sparse constant coefficients 

### ISSUE THREAD

**Issue by bamos** [locuslab/qpth#5]
+ Depends on https://github.com/pytorch/pytorch/issues/1178

**Comment by jdily** [comment]
Hi, does this means there is sparse solver in qpth?
Originally I read the paper and it mentioned only dense matrix is involved.
But if we can have sparse solver it will be pretty cool I think!! 👍 

Can you also point out how to use them ?
thx!

**Comment by bamos** [comment]
Hi, I just pushed an initial version of a sparse solver in this commit: https://github.com/locuslab/qpth/commit/babb0186c88cca4538dc08e9e3921f642481430b

I added an example use of it in the tests, but I'm probably going to change around the interface so I'm not yet going to add other docs for it. 

It also requires our `sparse_qr` branch of PyTorch:
https://github.com/locuslab/pytorch/tree/sparse_qr

**Comment by jdily** [comment]
this is quite awesome!
I will try to test it and will report it :)

**Comment by bamos** [comment]
Great! Do let us know how it's working for you. Also as another caveat, it currently only works with CUDA.

**Comment by jdily** [comment]
Hi, I recently get back to the need of sparse matrix solve.
And I  am curious about the function you used : `spbqrfactsolve`
According to the test in the `sparse_qr` branch, 
```    def test_spbqrfactsolve(self):
        nBatch, nx = 3, 5
        Ai = self.IndexTensor([range(nx), range(nx)])
        Av = self.ValueTensor(nBatch, nx).fill_(1.0)
        Asz = torch.Size([nx, nx])
        b = self.ValueTensor(nBatch, nx).uniform_()
        x_QR = torch.spbqrfactsolve(b, Ai, Av, Asz)
        self.assertEqual(x_QR, b)
```
It seems like the pattern of the different A matrix in this batch is the same, I am curious about if that is the case?

Because I am working on some problems, that involves different sparse matrices with different patterns across them.
And I am curious about should I look for something like the `btrifact()` and `btrisolve()` for dense tensors.
Do you have any suggestions or understanding of how to do that under current sparse tensor implementation in pytorch?

thx
